upstream backend { server backend:8000; }
upstream frontend { server frontend:80; }

server {
    listen 80;
    client_max_body_size 20M;

    location /api/   { proxy_pass http://backend; }
    location /docs   { proxy_pass http://backend; }
    location /openapi.json { proxy_pass http://backend; }
    location /receipts/ {
        proxy_pass http://backend;
    }
    location / { proxy_pass http://frontend; }
}